# -*- coding: utf-8 -*-
"""HotDog_Classifier_AliBakhsh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AM881NyfTQVMgCJPx8BP3iwcSOScT5lI
"""

# 1. Install Ultralytics
!pip install ultralytics -q

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow # Use this for Google Colab
# import matplotlib.pyplot as plt # Use this if NOT in Colab

# 2. Load the pre-trained Nano model
yolo_model = YOLO("yolov8n.pt")

# 3. Define the image URL
img_url = "https://www.shutterstock.com/image-photo/delicious-hot-dogs-sauces-lettuce-600w-2652600935.jpg"

# 4. Run detection (YOLOv8 can download directly from a URL)
results = yolo_model(img_url)

# 5. Plot the results (this draws the boxes and labels)
res_plotted = results[0].plot()

# 6. Display the image
print("YOLOv8 Detection Results:")
cv2_imshow(res_plotted)

# Optional: Print out exactly what it found
for box in results[0].boxes:
    class_id = int(box.cls[0])
    label = yolo_model.names[class_id]
    conf = float(box.conf[0])
    print(f"Found: {label} with {conf:.2f} confidence")

import numpy as np
import requests
from io import BytesIO
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

def predict_image(img_url):
    # 1. Download image
    try:
        response = requests.get(img_url)
        img = image.load_img(BytesIO(response.content), target_size=(IMG_HEIGHT, IMG_WIDTH))

        # 2. Preprocess the image
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) / 255.0  # Rescale to [0,1]

        # 3. Predict using your final trained model
        prediction = final_model.predict(img_array)[0][0]

        # 4. Interpret the sigmoid output (0 to 1)
        if prediction > 0.5:
            print(f"HOT DOG! (Confidence: {prediction:.2f})")
        else:
            print(f"NOT A HOT DOG! (Confidence: {1 - prediction:.2f})")

        # 5. Show the image we just predicted
        plt.imshow(img)
        plt.axis('off')
        plt.show()

    except Exception as e:
        print(f"Error loading image: {e}")

# REPLACE the URL below with a real link to a hot dog photo from Google Images
predict_image("https://www.shutterstock.com/image-photo/delicious-hot-dogs-sauces-lettuce-600w-2652600935.jpg")

import matplotlib.pyplot as plt

# Fixed syntax: straight quotes and no spaces around the dots
plt.plot(history_cnn.history['val_accuracy'], label='CNN (Overfit)', marker='o')
plt.plot(history_final.history['val_accuracy'], label='CNN + Dropout + Augment', marker='s')

plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.legend()
plt.title('Improving Generalization')
plt.grid(True)
plt.show()

# Create augmented data generator
augmented_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    validation_split=0.2
)

# Use the augmented generator for training
train_augmented = augmented_datagen.flow_from_directory(
    train_path,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training'
)

# Define the final model (Improved architecture + Dropout)
final_model = keras.Sequential([
    layers.Input(shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

# Compile
final_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train using the augmented data
history_final = final_model.fit(
    train_augmented,
    validation_data=validation_generator,
    epochs=15
)

from tensorflow.keras import regularizers

# Improved model with Dropout layers to stop overfitting
improved_model = keras.Sequential([
    # First Block
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25), # 25% dropout

    # Second Block
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25), # 25% dropout

    # Third Block
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.5),  # 50% dropout before flattening

    # Classification Head
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.5), # 50% dropout before output
    layers.Dense(1, activation='sigmoid')
])

# Recompile and Train
improved_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_improved = improved_model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=15
)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

# Plotting the validation accuracy for both models
plt.plot(history_ann.history['val_accuracy'], label='ANN Validation', marker='o')
plt.plot(history_cnn.history['val_accuracy'], label='CNN Validation', marker='s')

plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.legend()
plt.title('ANN vs CNN Validation Accuracy')
plt.grid(True)
plt.show()

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# REDEFINE THESE HERE so the model knows the input size
IMG_HEIGHT = 128  # or 64, depending on what you chose earlier
IMG_WIDTH = 128
BATCH_SIZE = 32

# Build the CNN
cnn_model = keras.Sequential([
    # First Conv layer: 32 filters, 3x3 kernel
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    layers.MaxPooling2D((2, 2)),

    # Second Conv layer: 64 filters
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Third Conv layer
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Flatten and dense layers
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
cnn_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train the CNN
history_cnn = cnn_model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=15
)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# Build a simple ANN
ann_model = keras.Sequential([
    # Flatten the 2D image (128x128x3) into a 1D vector
    layers.Flatten(input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),

    # Dense layers
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),

    # Output layer: sigmoid is used for binary (hot dog vs not)
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
ann_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Show model summary
ann_model.summary()

# Train for 10 epochs
history_ann = ann_model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10
)

# Plot training vs validation accuracy
plt.figure(figsize=(10, 6))
plt.plot(history_ann.history['accuracy'], label='Train Accuracy')
plt.plot(history_ann.history['val_accuracy'], label='Validation Accuracy')
plt.title('ANN Training vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Updated image size to 128x128
IMG_HEIGHT = 128
IMG_WIDTH = 128
BATCH_SIZE = 32

# Create generators with automatic labeling
train_datagen = ImageDataGenerator(
    rescale=1./255,          # Normalize pixel values
    validation_split=0.2     # Use 20% for validation
)

# Setup the training generator
train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training'
)

# Setup the validation generator
validation_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation'
)

# Print the class labels to verify
print(f"Class indices: {train_generator.class_indices}")

import matplotlib.pyplot as plt
import random
import os

# Display 6 random images
plt.figure(figsize=(12, 6))
for i in range(6):
    # Pick random class - Fixed the spaces inside the strings
    class_name = random.choice(["hot_dog", "not_hot_dog"])
    class_path = os.path.join(train_path, class_name)
    img_name = random.choice(os.listdir(class_path))
    img_path = os.path.join(class_path, img_name)

    # Load and show image
    img = plt.imread(img_path)
    plt.subplot(2, 3, i + 1)
    plt.imshow(img)
    plt.title(class_name)
    plt.axis('off')

plt.tight_layout()
plt.show()

# YOUR CODE HERE: Print the shape
print(f"Image shape (height, width, channels): {img.shape}")

import os

# Updated paths based on your Kaggle folder structure
train_path = "/kaggle/input/hot-dog-not-hot-dog/train"
test_path = "/kaggle/input/hot-dog-not-hot-dog/test"

# Count training images
hot_dog_count = len(os.listdir(os.path.join(train_path, "hot_dog")))
not_hot_dog_count = len(os.listdir(os.path.join(train_path, "not_hot_dog")))

print(f"Hot dog images: {hot_dog_count}")
print(f"Not hot dog images: {not_hot_dog_count}")

# YOUR CODE HERE: Count test images
test_hot_dog_count = len(os.listdir(os.path.join(test_path, "hot_dog")))
test_not_hot_dog_count = len(os.listdir(os.path.join(test_path, "not_hot_dog")))

print(f"Test Hot dog images: {test_hot_dog_count}")
print(f"Test Not hot dog images: {test_not_hot_dog_count}")

import numpy as np
import matplotlib . pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow . keras import layers
from tensorflow . keras . preprocessing . image import ImageDataGenerator
import os
import random
print ( " Libraries loaded successfully ! " )
print ( " TensorFlow version : " , tf . __version__ )

import kagglehub

# Download latest version
path = kagglehub.dataset_download("dansbecker/hot-dog-not-hot-dog")

print("Path to dataset files:", path)